### PR TITLE
Pandas 1.0 compatibility update

### PR DESCRIPTION
**Pull request by joejoezz**
Replaced the "aggregate" function with resample in the spot that it was causing problems. I think this fixes the issue but you might want to double-check that I didn't introduce any mystery bugs.

### CODE REVIEW

**Comment by jweyn** [comment]
Still not sure why line 260 works fine...

**Comment by joejoezz** [comment]
Did you get this error:
*** pandas.core.base.SpecificationError: nested renamer is not supported

**Comment by joejoezz** [comment]
I'm completely confused as to why 260 doesn't throw an error. I think it should throw one if the second instance does

**Comment by jweyn** [comment]
No, how did you get that error?

**Comment by jweyn** [comment]
Oh I think I see what may be going on. In the second case, the aggregate dictionary contained two aggregates for temperature (max and min). After applying aggregate it resulted in multi-index labels for the two columns for max and min temperatures. Then there must have been a change in how you are allowed to rename columns, and it wasn't compatible with the multi-index labels. This is not the case for the first groupby aggregation.

**Comment by jweyn** [comment]
So it wasn't the groupby after all that was responsible for breaking things, just the renaming later. Nevertheless it seems to me that resample does the same thing and is probably the recommended way to perform the operation we want.

**Pull request merged**
